// Turning a vendor's map coordinate into a pixel on the minimap.
//
// A direct port of ro_minimap.project in the overlay, and the comment there is
// worth repeating because the naive version looks right and is wrong: the
// image is not a picture of the map, it is a picture of the map's bounding
// *square*. A 320x240 map is drawn into a square bitmap with the short axis
// centred, so scaling a coordinate by the image's pixel size puts the pin off
// by half the difference on every non-square map - plausibly, which is worse
// than obviously.
//
// maps.json is generated by packet_probe/build_market_maps.py alongside the
// PNGs, from the same .gat dimensions the client uses.
import maps from "../data/maps.json";

type MapInfo = { cells: [number, number]; shared: boolean };

const INDEX = maps as unknown as Record<string, MapInfo>;

export function hasMinimap(map: string | null | undefined): boolean {
  return Boolean(map && INDEX[map]);
}

export function minimapUrl(map: string): string {
  return `${import.meta.env.BASE_URL}minimaps/${map}.png`;
}

export function cellSize(map: string): [number, number] | null {
  return INDEX[map]?.cells ?? null;
}

/** Map cell (x, y) -> pixel on a size x size minimap, or null if unknown. */
export function project(
  map: string | null | undefined,
  x: number | null | undefined,
  y: number | null | undefined,
  size: number,
): { px: number; py: number } | null {
  if (!map || x == null || y == null) return null;
  const dims = INDEX[map]?.cells;
  if (!dims) return null;
  const [w, h] = dims;
  const span = Math.max(w, h);
  const f = size / span;
  return {
    px: ((span - w) / 2 + x) * f,
    // y counts up from the bottom in game and down in pixels.
    py: ((h - span) / 2) * f + size - y * f,
  };
}
