import { SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import type { Query } from "../lib/api";
import cards from "../data/cards.json";
import maps from "../data/maps.json";
import options from "../data/options.json";

const CARDS = cards as Record<string, string>;
const MAPS = Object.keys(maps as Record<string, unknown>).sort();

// The random-option filter list comes from the client's own option table,
// generated by build_market_seed.py --web. Hand-writing it means guessing
// what index 17 is, and a wrong guess filters for the wrong stat while
// looking entirely correct on the page.
const OPTIONS = options as [number, string][];

const SORTS: [NonNullable<Query["sort"]>, string][] = [
  ["price_asc", "Cheapest first"],
  ["price_desc", "Most expensive"],
  ["time_desc", "Most recent"],
];

export function Filters({
  query,
  onChange,
}: {
  query: Query;
  onChange: (patch: Partial<Query>) => void;
}) {
  const [open, setOpen] = useState(false);
  const cardOptions = Object.entries(CARDS).sort((a, b) => a[1].localeCompare(b[1]));
  const active =
    (query.refine ? 1 : 0) +
    (query.card_id ? 1 : 0) +
    (query.opt_id ? 1 : 0) +
    (query.map ? 1 : 0) +
    (query.min_price || query.max_price ? 1 : 0);

  return (
    <div className="rounded-lg border border-slate-700/70 bg-slate-900/40">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className="flex w-full items-center gap-2 px-3 py-2 text-sm text-slate-300"
        aria-expanded={open}
      >
        <SlidersHorizontal className="h-4 w-4" />
        Filters
        {active > 0 && (
          <span className="rounded-full bg-sky-500/20 px-2 py-0.5 text-[11px] text-sky-200">
            {active}
          </span>
        )}
        <span className="ml-auto text-xs text-slate-500">{open ? "hide" : "show"}</span>
      </button>

      {open && (
        <div className="grid gap-4 border-t border-slate-700/70 p-3 sm:grid-cols-2">
          <label className="text-xs text-slate-400">
            Minimum refine: <span className="text-slate-200">+{query.refine ?? 0}</span>
            <input
              type="range"
              min={0}
              max={10}
              value={query.refine ?? 0}
              onChange={(e) => onChange({ refine: Number(e.target.value) || undefined })}
              className="mt-1 w-full accent-sky-500"
            />
          </label>

          <label className="text-xs text-slate-400">
            Sort
            <select
              value={query.sort ?? "price_asc"}
              onChange={(e) => onChange({ sort: e.target.value as Query["sort"] })}
              className="mt-1 w-full rounded border border-slate-700 bg-slate-900 px-2 py-1.5 text-sm text-slate-200"
            >
              {SORTS.map(([v, label]) => (
                <option key={v} value={v}>
                  {label}
                </option>
              ))}
            </select>
          </label>

          <label className="text-xs text-slate-400">
            Card slotted
            <select
              value={query.card_id ?? ""}
              onChange={(e) => onChange({ card_id: Number(e.target.value) || undefined })}
              className="mt-1 w-full rounded border border-slate-700 bg-slate-900 px-2 py-1.5 text-sm text-slate-200"
            >
              <option value="">any</option>
              {cardOptions.map(([id, name]) => (
                <option key={id} value={id}>
                  {name}
                </option>
              ))}
            </select>
          </label>

          <label className="text-xs text-slate-400">
            Random option
            <select
              value={query.opt_id ?? ""}
              onChange={(e) => onChange({ opt_id: Number(e.target.value) || undefined })}
              className="mt-1 w-full rounded border border-slate-700 bg-slate-900 px-2 py-1.5 text-sm text-slate-200"
            >
              <option value="">any</option>
              {OPTIONS.map(([id, label]) => (
                <option key={id} value={id}>
                  {label.replace(" +N", "").replace("N%", "%")}
                </option>
              ))}
            </select>
          </label>

          <label className="text-xs text-slate-400">
            Map
            <select
              value={query.map ?? ""}
              onChange={(e) => onChange({ map: e.target.value || undefined })}
              className="mt-1 w-full rounded border border-slate-700 bg-slate-900 px-2 py-1.5 text-sm text-slate-200"
            >
              <option value="">anywhere</option>
              {MAPS.map((m) => (
                <option key={m} value={m}>
                  {m}
                </option>
              ))}
            </select>
          </label>

          <div className="text-xs text-slate-400">
            Price range
            <div className="mt-1 flex items-center gap-2">
              <input
                type="number"
                min={0}
                placeholder="min"
                value={query.min_price ?? ""}
                onChange={(e) => onChange({ min_price: Number(e.target.value) || undefined })}
                className="w-full rounded border border-slate-700 bg-slate-900 px-2 py-1.5 text-sm text-slate-200"
              />
              <span className="text-slate-600">-</span>
              <input
                type="number"
                min={0}
                placeholder="max"
                value={query.max_price ?? ""}
                onChange={(e) => onChange({ max_price: Number(e.target.value) || undefined })}
                className="w-full rounded border border-slate-700 bg-slate-900 px-2 py-1.5 text-sm text-slate-200"
              />
            </div>
          </div>

          {active > 0 && (
            <button
              type="button"
              onClick={() =>
                onChange({
                  refine: undefined,
                  card_id: undefined,
                  opt_id: undefined,
                  map: undefined,
                  min_price: undefined,
                  max_price: undefined,
                })
              }
              className="justify-self-start rounded border border-slate-700 px-3 py-1.5 text-xs text-slate-300 hover:border-slate-500"
            >
              Clear filters
            </button>
          )}
        </div>
      )}
    </div>
  );
}
